=== m117stafa/tp-XML/Serie3_EX2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="characteristicValue">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="1.0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="logiciels" type="softwareList"></xs:element>
    <xs:complexType name="softwareList">
        <xs:sequence>
            <xs:element name="logiciel" maxOccurs="unbounded" type="software"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="software">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="createur" type="xs:string"/>
            <xs:element name="version" type="xs:string"/>
            <xs:element name="licence" type="xs:string"/>
            <xs:element name="plateforme" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="identifiant" type="xs:string"/>
            <xs:element name="langue" type="xs:string"/>
            <xs:element name="fonctionnalite" type="TYPE_FUNCTIONALITIES"/>
            <xs:element name="fiabilite" type="TYPE_FIABILITY"/>
            <xs:element name="utilisabilite" type="TYPE_USABILITY"/>
            <xs:element name="efficacite" type="TYPE_EFFICACITY"/>
            <xs:element name="maintenabilite" type="TYPE_MAINTENABILITY"/>
            <xs:element name="portabilite" type="TYPE_PORTABILITY"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TYPE_FUNCTIONALITIES">
        <xs:sequence>
            <xs:element name="aptitude" type="characteristicValue"/>
            <xs:element name="accuracy" type="characteristicValue"/>
            <xs:element name="interoperability" type="characteristicValue"/>
            <xs:element name="regulatoryCompliance" type="characteristicValue"/>
            <xs:element name="security" type="characteristicValue"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TYPE_FIABILITY">
        <xs:sequence>
            <xs:element name="maturity" type="characteristicValue"/>
            <xs:element name="faultTolerance" type="characteristicValue"/>
            <xs:element name="recoverability" type="characteristicValue"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TYPE_USABILITY">
        <xs:sequence>
            <xs:element name="comprehensibility" type="characteristicValue"/>
            <xs:element name="easeOfLearning" type="characteristicValue"/>
            <xs:element name="exploitability" type="characteristicValue"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TYPE_EFFICACITY">
        <xs:sequence>
            <xs:element name="resourceEfficiency" type="characteristicValue"/>
            <xs:element name="timeEfficiency" type="characteristicValue"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TYPE_MAINTENABILITY">
        <xs:sequence>
            <xs:element name="testability" type="characteristicValue"/>
            <xs:element name="stability" type="characteristicValue"/>
            <xs:element name="modifiability" type="characteristicValue"/>
            <xs:element name="analyzability" type="characteristicValue"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TYPE_PORTABILITY">
        <xs:sequence>
            <xs:element name="interchangeability" type="characteristicValue"/>
            <xs:element name="portabilityCompliance" type="characteristicValue"/>
            <xs:element name="installability" type="characteristicValue"/>
            <xs:element name="adaptability" type="characteristicValue"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <!-- définition de type pour les caractéristiques de qualité -->
    <!--<xs:simpleType name="characteristicValue">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="1.0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-\- définition de type pour les métadonnées du logiciel -\->
    <xs:simpleType name="softwareMetadata">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Win"/>
            <xs:enumeration value="Unix"/>
            <xs:enumeration value="Mac"/>
        </xs:restriction>
    </xs:simpleType>
    <!-\- définition de type pour le type de licence -\->
    <xs:simpleType name="softwareLicence">
        <xs:restriction base="xs:string">
            <xs:enumeration value="payant"/>
            <xs:enumeration value="free"/>
            <xs:enumeration value="shareware"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-\- définition de l'élément racine -\->
    <xs:element name="softwareQualityList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="software" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="creator" type="xs:string"/>
                            <xs:element name="version" type="xs:string"/>
                            <xs:element name="licence" type="softwareLicence"/>
                            <xs:element name="platform" type="softwareMetadata"/>
                            <xs:element name="date" type="xs:date"/>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="language" type="xs:string"/>
                            <xs:element name="functionality">
                                <xs:complexType >
                                    <xs:sequence>
                                        <xs:element name="aptitude" type="characteristicValue"/>
                                        <xs:element name="accuracy" type="characteristicValue"/>
                                        <xs:element name="interoperability" type="characteristicValue"/>
                                        <xs:element name="regulatoryCompliance" type="characteristicValue"/>
                                        <xs:element name="security" type="characteristicValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="reliability">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="maturity" type="characteristicValue"/>
                                        <xs:element name="faultTolerance" type="characteristicValue"/>
                                        <xs:element name="recoverability" type="characteristicValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="usability">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="comprehensibility" type="characteristicValue"/>
                                        <xs:element name="easeOfLearning" type="characteristicValue"/>
                                        <xs:element name="exploitability" type="characteristicValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="efficiency">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="resourceEfficiency" type="characteristicValue"/>
                                        <xs:element name="timeEfficiency" type="characteristicValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="maintainability">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="testability" type="characteristicValue"/>
                                    <xs:element name="stability" type="characteristicValue"/>
                                    <xs:element name="modifiability" type="characteristicValue"/>
                                    <xs:element name="analyzability" type="characteristicValue"/>
                                </xs:sequence>
                            </xs:complexType>
                            </xs:element>
                            <xs:element name="portability">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="interchangeability" type="characteristicValue"/>
                                        <xs:element name="portabilityCompliance" type="characteristicValue"/>
                                        <xs:element name="installability" type="characteristicValue"/>
                                        <xs:element name="adaptability" type="characteristicValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
    </xs:element>-->

=== m117stafa/tp-XML/SERIE3_EX2.xml
<?xml version="1.0" encoding="UTF-8"?>
<logiciels 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SERIE3_EX2.xsd">
    <logiciel>
        <nom>Logiciel Educatif </nom>
        <createur>Créateur 1</createur>
        <version>1.0</version>
        <licence>payant</licence>
        <plateforme>Win</plateforme>
        <date>2022-01-01</date>
        <identifiant>1</identifiant>
        <langue>fr</langue>
        <fonctionnalite>0.8</fonctionnalite>
        <fiabilite>0.9</fiabilite>
        <utilisabilite>0.7</utilisabilite>
        <efficacite>0.8</efficacite>
        <maintenabilite>0.6</maintenabilite>
        <portabilite>0.5</portabilite>
    </logiciel>
    <logiciel>
        <nom>Logiciel de streaming </nom>
        <createur>Créateur 2</createur>
        <version>2.0</version>
        <licence>free</licence>
        <plateforme>Unix</plateforme>
        <date>2022-02-02</date>
        <identifiant>2</identifiant>
        <langue>en</langue>
        <fonctionnalite>0.9</fonctionnalite>
        <fiabilite>0.8</fiabilite>
        <utilisabilite>0.4</utilisabilite>
        <efficacite>0.7</efficacite>
        <maintenabilite>0.5</maintenabilite>
        <portabilite>0.4</portabilite>
    </logiciel>
</logiciels>

=== m117stafa/tp-XML/SERIE3_EX2 (1).xml
<?xml version="1.0" encoding="UTF-8"?>
<logiciels 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SERIE3_EX2.xsd">
    <logiciel>
        <nom>Logiciel Educatif </nom>
        <createur>Créateur 1</createur>
        <version>1.0</version>
        <licence>payant</licence>
        <plateforme>Win</plateforme>
        <date>2022-01-01</date>
        <identifiant>1</identifiant>
        <langue>fr</langue>
        <fonctionnalite>
            <aptitude>0.3</aptitude>
            <accuracy>0.2</accuracy>
            <interoperability>0.2</interoperability>
            <regulatoryCompliance>0.4</regulatoryCompliance>
            <security>0.1</security>
        </fonctionnalite>
        <fiabilite>
            <maturity>0.2</maturity>
            <faultTolerance>0.4</faultTolerance>
            <recoverability>0.5</recoverability>
        </fiabilite>
        <utilisabilite>
            <comprehensibility>0.1</comprehensibility>
            <easeOfLearning>0.2</easeOfLearning>
            <exploitability>0.3</exploitability>
        </utilisabilite>
        <efficacite>
            <resourceEfficiency>0.1</resourceEfficiency>
            <timeEfficiency>0.2</timeEfficiency>
        </efficacite>
        <maintenabilite>
            <testability>0.1</testability>
            <stability>0.2</stability>
            <modifiability>0.4</modifiability>
            <analyzability>0.1</analyzability>
        </maintenabilite>
        <portabilite>
            <interchangeability>0.1</interchangeability>
            <portabilityCompliance>0.2</portabilityCompliance>
            <installability>0.3</installability>
            <adaptability>0.4</adaptability>
        </portabilite>
       
        <!--<fonctionnalite>0.8</fonctionnalite>
        <fiabilite>0.9</fiabilite>
        <utilisabilite>0.7</utilisabilite>
        <efficacite>0.8</efficacite>
        <maintenabilite>0.6</maintenabilite>
        <portabilite>0.5</portabilite>-->
    </logiciel>
    <logiciel>
        <nom>Logiciel </nom>
        <createur>Créateur 2</createur>
        <version>2.0</version>
        <licence>free</licence>
        <plateforme>Unix</plateforme>
        <date>2022-02-02</date>
        <identifiant>2</identifiant>
        <langue>en</langue>
        <fonctionnalite>
            <aptitude>0.3</aptitude>
            <accuracy>0.2</accuracy>
            <interoperability>0.2</interoperability>
            <regulatoryCompliance>0.4</regulatoryCompliance>
            <security>0.1</security>
        </fonctionnalite>
        <fiabilite>
            <maturity>0.2</maturity>
            <faultTolerance>0.4</faultTolerance>
            <recoverability>0.5</recoverability>
        </fiabilite>
        <utilisabilite>
            <comprehensibility>0.1</comprehensibility>
            <easeOfLearning>0.2</easeOfLearning>
            <exploitability>0.3</exploitability>
        </utilisabilite>
        <efficacite>
            <resourceEfficiency>0.1</resourceEfficiency>
            <timeEfficiency>0.2</timeEfficiency>
        </efficacite>
        <maintenabilite>
            <testability>0.1</testability>
            <stability>0.2</stability>
            <modifiability>0.4</modifiability>
            <analyzability>0.1</analyzability>
        </maintenabilite>
        <portabilite>
            <interchangeability>0.1</interchangeability>
            <portabilityCompliance>0.2</portabilityCompliance>
            <installability>0.3</installability>
            <adaptability>0.4</adaptability>
        </portabilite>
    </logiciel>
</logiciels>
